### ISSUE TITLE
请问一下

### ISSUE THREAD

**Issue by pedrogao** [xuyiqiang-learn/W2V_TextRank#1]
您好，我最近也在做文本摘要相关的工作，方向也是用word2vec和textrank的方法。请问一下，您用这种方法生成文本摘要的速度是不是很慢，相对于传统的textrank算法生成摘要？

**Comment by johnson-xu01** [comment]
速度很快！速度慢是因为第一次将词向量读入内存字典需要差不多一分钟的时间。如果是在应用场景，字典只需加载一次在内存中，后面调用接口生成摘要就很快。
